export {Header} from './Header'
export {Footer} from './Footer'
export {StickySlider,Slide} from './Slide'
export {Partner} from './Partner'
export {Card} from './Card'
export {Bonus} from './Bonus'
export {Baner} from './Baner'